# Generated by Django 5.0.8 on 2024-08-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_todo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
